# Generated by Django 6.0.1 on 2026-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tiff_file', models.FileField(upload_to='projects/tiffs/')),
                ('cached_flux', models.FloatField(blank=True, help_text='Predicted Carbon Flux', null=True)),
                ('cached_co2', models.FloatField(blank=True, help_text='Annual Tonnes CO2', null=True)),
                ('cached_revenue', models.FloatField(blank=True, help_text='Estimated Revenue USD', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
